pool:
    vmImage: 'Ubuntu 16.04'

variables:
    Version: '3.0.$(Build.BuildId)'

steps:
    - task: UseDotNet@2
      inputs:
          packageType: sdk
          version: 3.0.100-preview6-012264
          includePreviewVersions: true
    - task: DotNetCoreCLI@2
      inputs:
          command: restore
          projects: '**/*.csproj'
          feedsToUse: 'select'
          verbosityRestore: 'minimal'
          vstsFeed: 'BioEngine'
    - task: DotNetCoreCLI@2
      inputs:
          command: custom
          custom: build
          arguments: '--no-restore -c Release'
          projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
          command: pack
          nobuild: true
          configuration: 'Release'
          versioningScheme: byEnvVar
          versionEnvVar: 'Version'
          verbosityPack: 'minimal'
          packDirectory: '$(build.artifactStagingDirectory)'

    - task: DotNetCoreCLI@2
      inputs:
          command: push
          nuGetFeedType: 'internal'
          publishVstsFeed: 'BioEngine'
          versioningScheme: byEnvVar
          versionEnvVar: 'Version'
    - task: PublishPipelineArtifact@0
      inputs:
          artifactName: 'packages'
          targetPath: '$(Build.ArtifactStagingDirectory)'
